### ISSUE TITLE
minimal blog layout and modeling.

### ISSUE THREAD

**Issue by MSakamaki** [MSakamaki/scully-homepage#28]
# We need to decide what to do next.

Before implementing a minimum layout, we need to discussion UI/UX.

## Decided:

 - Minimum layout that works as a blog
 - filter function
 - Next, link to previous post
 - Desktop and smartphone layout

## Undecided matters:

 - [x] icon (favicon)
 - [x] logo image
 - [x] blog data model
 - [ ] ~~Playful layout~~
 
If there are any other missing features we need to discuss.

## images

<img width="773" alt="home" src="https://user-images.githubusercontent.com/2183053/96952490-f13bc280-1529-11eb-850a-e4aec1d025e7.png">
<img width="653" alt="blog" src="https://user-images.githubusercontent.com/2183053/96952492-f3058600-1529-11eb-9e47-4b143081073a.png">

**Comment by mihirogi** [comment]
@MSakamaki Maybe a blog category tag.It looks like a button.

**Comment by mihirogi** [comment]
I made a blog model.

Next, make a model in graphcm and put sample data.
