### ISSUE TITLE
Building a Lighthouse CI Server

### ISSUE THREAD

**Issue by MSakamaki** [MSakamaki/scully-homepage#50]
https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#the-lighthouse-ci-server

**Comment by mihirogi** [comment]
setup lhci-server
https://still-island-43535.herokuapp.com/app/projects/scully-homepage/dashboard

setting repository
https://github.com/mihirogi/wot-lhci-server

**Comment by mihirogi** [comment]
Once merged into the "main" branch, the results are sent to the lighthouse-ci-server.

If you want to periodically measure the results, you need to push an empty commit to "main" branch, as shown below
https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/troubleshooting.md#lhci-server-wont-let-me-upload-a-rerun-of-a-build
