### ISSUE TITLE
Notify a library update nrwl/nx version 10.4.4

### ISSUE THREAD

**Issue by mihirogi** [MSakamaki/scully-homepage#56]
https://github.com/nrwl/nx/releases/tag/10.4.4

**Comment by MSakamaki** [comment]
https://github.com/nrwl/nx/releases/tag/11.0.0

**Comment by MSakamaki** [comment]
https://nx.dev/latest/angular/workspace/update

Angular: https://v10.angular.io/guide/updating-to-version-10
Nrwl: https://nx.dev/latest/angular/cli/migrate.
